name: Laravel CI

on:
  push:
    branches:
      - develop
      - feature/**
  pull_request:
    branches:
      - develop
  workflow_dispatch: 
jobs:
  test:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - run: cp .env.example .env

      - run: php artisan key:generate

      - run: php artisan migrate

      - run: php artisan db:seed

      - run: php artisan test

      - run: ./vendor/bin/pint --test

      - run: ./vendor/bin/phpstan analyse

      - run: composer audit

      - run: zip -r release.zip .

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: release.zip
